# Generated by Django 5.1.3 on 2024-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bakery',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bread', 'Хлеб'), ('buns', 'Булочки'), ('cakes', 'Торты'), ('pastries', 'Пирожные'), ('croissants', 'Круассаны')], default='email', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
