# Generated by Django 5.1.3 on 2024-11-29 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0007_delivery_delivery_address_delivery_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deliveries',
            field=models.ManyToManyField(related_name='customers', to='bakery_app.delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
